Snips.addText("de", :switchon, "Ich schalte den Fernseher und Kodi ein. Bitte einen Moment Geduld")
Snips.addText("de", :switchoff, "Ich schalte den Fernseher und Kodi aus.")
Snips.addText("de", :ok, "OK.")
Snips.addText("de", :diy, "Ich öffne Kodi; bitte suche selbst aus, was Du sehen willst!")
Snips.addText("de", :i_play, "Ich spiele")
Snips.addText("de", :i_play_new_otr, "Ich spiele die nächste aufgenommene Folge")
Snips.addText("de", :season, "Staffel")
Snips.addText("de", :episode, "Folge")
Snips.addText("de", :episodes, "Folgen")
Snips.addText("de", :recordings, "Aufnahmen")
Snips.addText("de", :slideshows, "Diashows")
Snips.addText("de", :title_is, "der Titel ist")

Snips.addText("de", :i_search_for, "Ich suche nach")
Snips.addText("de", :i_search_show, "Ich suche in der Seriendatenbank nach")
Snips.addText("de", :i_search_movie, "Ich suche in der Filmdatenbank nach")
Snips.addText("de", :i_search_rec, "Ich suche in den Fernsehaufnahmen nach")
Snips.addText("de", :be_patient, "Bitte etwas Geduld Dies kann einen Moment dauern!")
Snips.addText("de", :found, "Gefunden")
Snips.addText("de", :fits, "passen zu deiner Anfrage")
Snips.addText("de", :new, "davon neu")

Snips.addText("de", :noip, "Ich finde die Adresse von Kodi nicht in der config Datei!")
Snips.addText("de", :dunno, "Ich habe nicht verstanden was ich tun soll!")
Snips.addText("de", :error_kodiCmd, "Ich kann den Kodi Befehl nicht ausführen.")
Snips.addText("de", :error_name, "Ich konnte leider nicht verstehen, welchen Film ich zeigen soll!")
Snips.addText("de", :error_name, "Ich möchte diesen Teppich bitte nicht kaufen!")
Snips.addText("de", :error_on, "Ich kann leider Kodi nicht einschalten!")
Snips.addText("de", :error_on_mode, "Ich weiß nicht wie ich Kodi einschalten soll!")

Snips.addText("de", :which_pictures, """Ich habe nicht verstanden,
        welche Fotos ich zeigen soll. Ich öffne die Datenbank!""")
Snips.addText("de", :be_precise, "Bitte präzisiere Deine Frage!")




Snips.addText("en", :switchon, "I have to power on the TV. Please be patient; this will take some time.")
Snips.addText("en", :switchoff, "T power off the TV and Kodi.")
Snips.addText("en", :ok, "OK.")
Snips.addText("en", :diy, "I open Kodi; please select in the menu what you want to see.")
Snips.addText("en", :i_play, "I start playing")
Snips.addText("en", :i_play_new_otr, "I play the next recording")
Snips.addText("en", :season, "season")
Snips.addText("en", :episode, "episode")
Snips.addText("en", :episodes, "episodes")
Snips.addText("en", :recordings, "recordings")
Snips.addText("en", :slideshows, "slide shows")
Snips.addText("en", :title_is, "the title is")

Snips.addText("en", :i_search_for, "I am looking for")
Snips.addText("en", :i_search_show, "I search the TV show database for")
Snips.addText("en", :i_search_movie, "I search the movie database for")
Snips.addText("en", :i_search_rec, "I serach the recordings for")
Snips.addText("en", :be_patient, "Please be patient; this might take a moment!")
Snips.addText("en", :found, "found")
Snips.addText("en", :fits, "fit to your request")
Snips.addText("en", :new, "unseen")

Snips.addText("en", :noip, "I cannot find the address of Kodi in the config.ini!")
Snips.addText("en", :dunno, "I don't know what to do!")
Snips.addText("en", :error_kodiCmd, "I cannot execute the Kodi command.")
Snips.addText("en", :error_name, "Unfortunately, I could not understand which movie I should show!")
Snips.addText("en", :error_on, "I can not turn Kodi on!")
Snips.addText("en", :error_on_mode, "I don't know how to switch on Kodi")

Snips.addText("en", :which_pictures, """I did not understand,
        which photos I should show. I open the database!""")

Snips.addText("en", :be_precise, "Please specify your question!")
