Snips.addText("de", :noip, "Ich finde die Adresse von Kodi nicht in der config Datei!")
Snips.addText("de", :dunno, "Ich habe nicht verstanden was ich tun soll!")
Snips.addText("de", :switchon, "Ich schalte den Fernseher und Kodi ein. Bitte einen Moment Geduld")
Snips.addText("de", :switchoff, "Ich schalte den Fernseher und Kodi aus.")
Snips.addText("de", :ok, "OK.")
Snips.addText("de", :error_kodiCmd, "Ich kann den Kodi Befehl nicht ausführen.")
Snips.addText("de", :error_name, "Ich konnte leider nicht verstehen, welchen Film ich zeigen soll!")
Snips.addText("de", :diy, "Ich öffne Kodi; bitte suche selbst aus, was Du sehen willst!")
Snips.addText("de", :i_play, "Ich spiele")
Snips.addText("de", :i_play_new_otr, "Ich spiele die nächste OTR-Aufnahme")
Snips.addText("de", :season, "Staffel")
Snips.addText("de", :episode, "Folge")
Snips.addText("de", :episodes, "Folgen")
Snips.addText("de", :recordings, "Aufnahmen")
Snips.addText("de", :title_is, "der Titel ist")
Snips.addText("de", :i_search_show, "Ich suche in der Seriendatenbank nach")
Snips.addText("de", :i_search_movie, "Ich suche in der Filmdatenbank nach")
Snips.addText("de", :i_search_rec, "Ich suche in den Fernsehaufnahmen nach")
Snips.addText("de", :found, "Gefunden")
Snips.addText("de", :new, "davon neu")



Snips.addText("en", :noip, "I am not able to find the IP address of kodi in config.ini")
Snips.addText("en", :dunno, "I don't know, what to do")
Snips.addText("en", :switchon, "I switch in the tv and kodi. Please be patient!")
Snips.addText("en", :switchoff, "I switch off the tv and kodi.")
Snips.addText("en", :ok, "OK.")
